'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace My.Resources

    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class Resources

        Private Shared _resourceMan As Global.System.Resources.ResourceManager
        Private Shared _resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        Friend Sub New()
            MyBase.New()
        End Sub

        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(_resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager =
                        New Global.System.Resources.ResourceManager(
                            "SPS_PortableAppTrack.Resources",
                            GetType(Resources).Assembly)
                    _resourceMan = temp
                End If
                Return _resourceMan
            End Get
        End Property

        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return _resourceCulture
            End Get
            Set(value As Global.System.Globalization.CultureInfo)
                _resourceCulture = value
            End Set
        End Property

    End Class

End Namespace
